### ISSUE TITLE
tg help summary fails on when $PAGER contains a complex command string

### ISSUE THREAD

**Issue by 4z3** [greenrd/topgit#36]
`tg help summary` fails at [tg.sh, line 462](https://github.com/greenrd/topgit/blob/3f164dccbbbd8ba73139599fa91211c8adc5dcca/tg.sh#L462) when `PAGER` contains a complex command strings like e.g. `less -R`.

According to [POSIX's man(1)](http://www.unix.com/man-page/posix/1/man/) `PAGER` may contain _any string acceptable as a command_string operand to the sh -c command_.

A possible solution to this problem would be to eval `TG_PAGER` or call it with `sh -c "$TG_PAGER"`.

Reference: http://lists.science.uu.nl/pipermail/nix-dev/2014-September/014244.html

**Comment by Profpatsch** [comment]
30 seconds of usage and the first bug. Nice!
