### ISSUE TITLE
not clear what  "autoremove (clean) up-to-date branches" means

### ISSUE THREAD

**Issue by imz** [greenrd/topgit#41]
<https://github.com/greenrd/topgit/blob/master/README#L602>:

	TODO: tg update -a -c to autoremove (clean) up-to-date branches

It's not clear what "autoremove (clean) up-to-date branches" means: a branch is simply a branch, what does mean that it is not "clean" and becomes "clean"?

**Comment by greenrd** [comment]
It means branches whose changes have already been merged in to the base branch and/or a dependency.
