### ISSUE TITLE
topgit upstream status

### ISSUE THREAD

**Issue by thmo** [greenrd/topgit#67]
While this repository seems to be not active within the last 1.5 years or so, there is a fork (not marked as a fork, but still) by @mackyle in https://github.com/mackyle/topgit, being more active in that time frame.

As the Fedora package maintainer I wonder whether I should switch upstreams.

There are a bunch of issues open here, and even pull requests, and I cannot easily see to which extent bugs have been solved and fixes incorporated in @mackyle's repo.

@greenrd, @mackyle: Any comments?

**Comment by mackyle** [comment]
@thmo,

I believe I've addressed all the bugs I could reproduce (I think some were overcome by events and rendered invalid by other changes I had made before I got around to looking at them) and some other issues as well.  Some differences are:

 1. Minimum Git version is now 1.8.5
 2. Once installed it's strictly POSIX + Git
 3. It's much faster (see <https://github.com/mackyle/topgit/commit/f7f852d1d06c7a66>)
 4. It handles current Git versions' idiosyncrasies (linked working trees, user.useConfigOnly=true, --allow-unrelated-histories)
 5. It has a form of undo (see <https://mackyle.github.io/topgit/topgit.html#no-undo>)
 6. tg update no longer spawns a subshell to resolve conflicts, instead you just `tg update --continue` once you've fixed them (and the new `tg status` command helps to remind you what you need to do)
 7. There's a test suite
 8. `tg update` can create octopus merges when there are no conflicts (and does so in a very fast index-only manner)

I've not touched `contrib/tg-completion.bash` though; I'm afraid that may be a bit outdated at this point.

The documentation has been substantially updated.  The nicely formatted versions of the ChangeLog and Documentation are linked from <https://mackyle.github.io/topgit/>.

**Comment by greenrd** [comment]
Good to see someone has given topgit some love while I've been neglecting it. I'm happy to point users to the @mackyle repo and mark mine as unmaintained.

I may return to topgit and submit PRs to mackyle's version in the future - who knows.
